### ISSUE TITLE
Publish to sg zip package seems to exclude .pyc files?

### ISSUE THREAD

**Issue by RicardoMusch** [cpenv/tk-cpenv#11]
I noticed that when publishing to SG the zip files do not include .pyc files.
Not sure if this is by design but a plugin like animbot seems to break because of this.
I manually fixed it by replacing the zip file with one that has all files.

**Comment by danbradham** [comment]
Oh yeah. That makes sense, I didn't consider folks who only ship .pyc files with their plugins. Strange practice if you ask me haha, super easy to decompile those things. I should have time to patch this in the next few days.

**Comment by danbradham** [comment]
This has been resolved. If you install the latest version of cpenv, it should keep prebuilt .pyc files when publishing. I plan on adding support for `.ignore` files in modules. These would function like `.gitignore` files and allow module authors to specify which files are included when publishing.
