### ISSUE TITLE
[Bug] Localize dialog displays the wrong package it's caching

### ISSUE THREAD

**Issue by RicardoMusch** [cpenv/tk-cpenv#14]
The package it's localizing here is not the one displayed on the label.

![image](https://user-images.githubusercontent.com/54025297/159523615-a0ef9f9f-3473-4446-a51f-152326d8b82b.png)

**Comment by danbradham** [comment]
Fixed in v0.5.7

**Comment by RicardoMusch** [comment]
Awesome! Was gonna dig in myself on the weekend haha.

Cheers!
