### ISSUE TITLE
Removing a module from ShotGrid causes GUI to break

### ISSUE THREAD

**Issue by fabiangeisler** [cpenv/tk-cpenv#19]
If you remove a module from ShotGrid and that is referenced in the environment that is about to be loaded in the tk-cpenv GUI, you will get an error dialog and the GUI wont show. 

Manually fixing the environment in ShotGrid does work but is not particularly elegant. Would be nice to have some nice feedback about that in the interface, like missing modules marked in red or something.

**Comment by danbradham** [comment]
Thanks for reporting! I like the idea of marking the missing modules as well.
